- name: Rocket hardware setup
  hosts: rocket,&pi
  become: true
  gather_facts: false
  tasks:
    - name: Copy config.txt
      ansible.builtin.copy:
        src: config.txt
        dest: /boot/config.txt
        owner: root
        mode: 0755 # FAT doesn't support executable bit
      notify: Reboot

    - name: Copy modules-load.d/i2c-dev.conf
      ansible.builtin.copy:
        src: i2c-dev.conf
        dest: /etc/modules-load.d/i2c-dev.conf
        owner: root
        mode: 0644
      notify: Reboot

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

- name: Generic pi system setup
  hosts: pi
  become: true
  gather_facts: false
  tasks:
    - name: Disable and stop packagekit
      ignore_errors: true
      # Uses a lot of CPU, doesn't do anything useful
      ansible.builtin.systemd:
        name: packagekit
        enabled: false
        state: stopped

- name: Vagrant system setup
  hosts: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Add vagrant user to groups
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - systemd-journal

    - name: Copy resolv.conf from host
  # Rose-Hulman's network blocks outgoing DNS connections to public servers, so copying the resolv.conf from the host allows the VM to use Rose's server
      ansible.builtin.copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        mode: 0444 # Read Only
