- name: Install and setup sensord
  hosts: rocket,&pi
  vars:
    lse_pip_url: https://github.com/Rose-Rocketry/lib_sensor_encoding/archive/v0.0.4.tar.gz
    venv: /opt/sensord_venv
    units:
      - sensord@system.service
      - sensord@mpu6050.service
      - sensord@mpl3115.service
      - sensord@gpsd.service
  gather_facts: false
  become: true
  tasks:
    - name: Install pip
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
    - name: Setup venv
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv
        virtualenv: "{{ venv }}"
        name: 
          - "{{ lse_pip_url }}"
          - Adafruit_PureIO
          - psutil
      notify: Restart sensord
    - name: Copy source
      ansible.posix.synchronize:
        src: src/
        dest: /opt/sensord/
        archive: no
        checksum: yes
        delete: yes
        recursive: yes
      notify: Restart sensord
    - name: Copy sensord@.service
      ansible.builtin.copy:
        src: sensord@.service
        dest: /etc/systemd/system
        owner: root
        mode: 0644
      notify: Restart sensord
    - name: Enable sensord.service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ units }}"

  handlers:
    - name: Restart sensord
      ansible.builtin.systemd:
        name: "{{ item }}"
        daemon_reload: true
        state: restarted
      loop: "{{ units }}"
