- name: Install and setup mosquitto
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install mosquitto
      ansible.builtin.apt:
        name: mosquitto

    - name: Copy rsmb.service
      ansible.builtin.copy:
        src: rocket.conf
        dest: /etc/mosquitto/conf.d/rocket.conf
        mode: 0644
      notify: Restart mosquitto

    - name: Enable mosquitto service
      ansible.builtin.systemd:
        name: mosquitto
        state: started
        enabled: true


  handlers:
    - name: Restart mosquitto
      ansible.builtin.systemd:
        name: mosquitto
        daemon_reload: true
        state: restarted
