- name: Install and setup XBNet
  hosts: pi
  vars:
    github_repo: https://github.com/Rose-Rocketry/xbnet
  gather_facts: true
  become: true
  tasks:
    - name: Download latest binary
      ansible.builtin.get_url:
        url: "{{ github_repo }}/releases/latest/download/xbnet-{{ ansible_facts['machine'].removesuffix('v6l') }}"
        checksum: sha256:{{ github_repo }}/releases/latest/download/xbnet-{{ ansible_facts['machine'].removesuffix('v6l') }}.sha256
        dest: /usr/local/bin/xbnet
        mode: 0755
      notify: Restart XBNet

    - name: Generate xb-initfile.txt
      ansible.builtin.template:
        src: ./xb-initfile.txt.j2
        dest: /usr/local/etc/xb-initfile.txt
        mode: 0644
      notify: Restart XBNet

    - name: Generate xbnet.service
      ansible.builtin.template:
        src: xbnet.service.j2
        dest: /etc/systemd/system/xbnet.service
        mode: 0644
      register: sdr_unit
      notify: Restart XBNet

    - name: Enable xbnet.service
      ansible.builtin.systemd:
        name: xbnet
        enabled: true
        state: started

  handlers:
    - name: Restart XBNet
      ansible.builtin.systemd:
        name: xbnet
        daemon_reload: true
        state: restarted

- name: Simulate radio link on VM's
  hosts: vagrant
  gather_facts: false
  become: true
  tasks:
    - name: Create TC rules
      # TODO: Measure these values more precisely
      ansible.builtin.command: tc qdisc replace dev eth1 root netem rate 60kbit delay 50ms loss 1%
      changed_when: true
