- name: Install and setup RSMB
  hosts: all
  vars:
    github_repo: https://github.com/Rose-Rocketry/mosquitto.rsmb
  gather_facts: true
  become: true
  tasks:
    - name: Download latest binary
      ansible.builtin.get_url:
        url: "{{ github_repo }}/releases/latest/download/rsmb-{{ ansible_facts['machine'].removesuffix('v6l') }}"
        checksum: sha256:{{ github_repo }}/releases/latest/download/rsmb-{{ ansible_facts['machine'].removesuffix('v6l') }}.sha256
        dest: /usr/local/bin/rsmb
        mode: 0755
      notify: Restart RSMB

    - name: Generate rsmb.conf
      ansible.builtin.template:
        src: ./rsmb.conf.j2
        dest: /usr/local/etc/rsmb.conf
        mode: 0644
      notify: Restart RSMB

    - name: Copy rsmb.service
      ansible.builtin.copy:
        src: rsmb.service
        dest: /etc/systemd/system/
        mode: 0644
      notify: Restart RSMB

    - name: Enable rsmb.service
      ansible.builtin.systemd:
        name: rsmb
        enabled: true
        state: started

  handlers:
    - name: Restart RSMB
      ansible.builtin.systemd:
        name: rsmb
        daemon_reload: true
        state: restarted
