- ansible.builtin.import_playbook: system/playbook.yaml
- ansible.builtin.import_playbook: xbnet/playbook.yaml
- ansible.builtin.import_playbook: rsmb/playbook.yaml
- ansible.builtin.import_playbook: sdr/playbook.yaml
- ansible.builtin.import_playbook: direwolf/playbook.yaml
- ansible.builtin.import_playbook: gps/playbook.yaml
