Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  config.vm.define "groundstation-vagrant" do |config|
    config.vm.hostname = "groundstation"
    config.vm.network "private_network", ip: "10.82.104.1"
  end

  config.vm.define "rocket-vagrant" do |config|
    config.vm.hostname = "rocket"
    config.vm.network "private_network", ip: "10.82.104.2"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.groups = {
      "groundstation" => ["groundstation-vagrant"],
      "rocket" => ["rocket-vagrant"],
      "vagrant" => ["groundstation-vagrant", "rocket-vagrant"]
    }
  end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
